name = "MathOptLazy"
uuid = "5d5fe9b5-b0a4-4485-81f6-7b1b939155e1"
version = "0.1.0"
authors = ["Oscar Dowson <o.dowson@gmail.com>"]

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[weakdeps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[extensions]
MathOptLazyJuMPExt = "JuMP"

[compat]
JuMP = "1"
MathOptInterface = "1"
julia = "1.10"
